name: Language plugin

on: [push]

jobs:
  test:
    name: Language plugin
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/reason-relay/language-plugin
    container:
      image: cichocinski/docker-esy:alpine3.8
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12.19.0
        env:
          CI: true
      - name: Set up yarn
        run: apk add --no-cache yarn
      - name: Install
        run: |
          yarn --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Esy install
        run: esy install
      - name: Build PPX
        run: esy linux-release-static
      - name: Copy built ReasonRelayBin file
        working-directory: packages/reason-relay-bin
        run: |
          ./copyIntoPlace.sh
      - name: Test
        run: |
          yarn test:ci
